### ISSUE TITLE
Add instructions about the tip Coinvise command not being usable from mobile

### ISSUE THREAD

**Issue by alecrem** [henkaku-center/henkaku-community#10]
As proposed by @RyuKiyo66 on #8

> チップコマンドは、iPhone/iPadなどのdiscordアプリからは使えず（バグ？）、PCから使うしかないようです。このような説明も必要だと思いますが、いかがでしょうか？

確認事項:

- c!tip コマンドをモバイルで使おうとすると、FAQにある`チップコマンドを送ったら「Invalid format」が返ってきました`と同じ結果になるでしょうか、それともFAQに別のQを追加した方がいいでしょうか？

**Comment by RyuKiyo66** [comment]
同じコメントです

**Comment by RyuKiyo66** [comment]
![876347FB-063A-4587-A279-27504592326C](https://user-images.githubusercontent.com/96900106/147827850-244e6239-ec41-449a-b5be-7f3ccd1d5de4.jpeg)

**Comment by alecrem** [comment]
ありがとうございます！

`c!register`コマンドを繰り返してから`c!tip`をやり直しても使えないということですね。

ボットの新しいバージョンがインストールされましたけど、こういうところが改善されているか確認したいですね。

**Comment by Joi** [comment]
The new bot uses `/register` and `/tip` ... but still seems a bit buggy.

**Comment by alecrem** [comment]
I think we can close this as per #11

> チップコマンドは、iPhone/iPadなどのdiscordアプリからは使えず（バグ？）、PCから使うしかないようです。このような説明も必要だと思いますが、いかがでしょうか？

[From your PC, please follow the steps below (Chrome and Brave are recommended).](https://henkaku.gitbook.io/community/henkaku-token)

(I did just fine with Firefox, and wonder if we should add it)

> The new bot uses `/register` and `/tip` ... but still seems a bit buggy.

[Confirm that the format was correct: `/tip token:henkaku network: Matic/Polygon`](https://henkaku.gitbook.io/community/faq)
